import localFont from 'next/font/local'
import '../src/styles/global.scss'

const SpaceGroteskbold = localFont({
  src: '../public/fonts/static/SpaceGrotesk-Bold.ttf',
})
const SpaceGroteskmed = localFont({
  src: '../public/fonts/static/SpaceGrotesk-Medium.ttf',
})
const SpaceGroteskVar = localFont({
  src: '../public/fonts/SpaceGrotesk-VariableFont_wght.ttf',
})

export const metadata = {
  title: 'shane portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${SpaceGroteskbold.className} ${SpaceGroteskVar.className} ${SpaceGroteskmed.className}`}
      >
        {children}
      </body>
    </html>
  )
}
